Update

diff --git a/.github/workflows/maxcso-build.yml b/.github/workflows/maxcso-build.yml
--- a/.github/workflows/maxcso-build.yml
+++ b/.github/workflows/maxcso-build.yml
@@ -29,16 +29,16 @@ jobs:
       matrix:
         include:
           - docker_image: i386/ubuntu:latest
-            docker_arch: 386
+            docker_arch: linux/386
             nodejs_arch: ia32
           - docker_image: ubuntu:latest
-            docker_arch: amd64
+            docker_arch: linux/amd64
             nodejs_arch: amd64
           - docker_image: ubuntu:latest
-            docker_arch: arm/v7
+            docker_arch: linux/arm/v7
             nodejs_arch: armv7
           - docker_image: ubuntu:latest
-            docker_arch: arm64/v8
+            docker_arch: linux/arm64/v8
             nodejs_arch: arm64v8
     steps:
       - uses: actions/checkout@v4
@@ -49,9 +49,10 @@ jobs:
       - run: |
           {
             echo "#!/usr/bin/env bash"
+            echo "set -euo pipefail"
 
-            echo "apt-get update"
-            echo "apt-get install -y build-essential pkgconf zlib1g-dev liblz4-dev libuv1-dev"
+            echo "sudo apt-get update"
+            echo "sudo apt-get install -y build-essential pkgconf zlib1g-dev liblz4-dev libuv1-dev"
             echo "make -j$(nproc)"
 
             echo "apt-get install -y binutils"
@@ -62,10 +63,10 @@ jobs:
           chmod +x build.sh
       - run: |
           docker run --rm \
-            --platform "linux/${DOCKER_ARCH}" \
+            --platform "${DOCKER_ARCH}" \
             --volume "$(pwd):/build" \
             --workdir "/build" \
-            ubuntu:latest
+            "${DOCKER_IMAGE}"
             ./build.sh
         env:
           DOCKER_IMAGE: ${{ matrix.docker_image }}
